vich_uploader:
    db_driver: orm
    mappings:
        ticket_attachments:
            uri_prefix: /uploads/tickets
            upload_destination: '%kernel.project_dir%/public/uploads/tickets'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 